### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by danielckv** [twilio/twilio-node#117]
After npm install a few days ago, our app started to crash each time. I tried to figure out what is the problem but didn't find any solution for this:

at Function.generate.restFunctions (/node_modules/twilio/lib/resources/generate.js:89:50)
    at module.exports (/node_modules/twilio/lib/resources/ListInstanceResource.js:29:14)
    at mixinResources (/node_modules/twilio/lib/resources/Accounts.js:18:31)
    at module.exports (/node_modules/twilio/lib/resources/Accounts.js:109:5)
    at new RestClient (/node_modules/twilio/lib/RestClient.js:28:58)
    at initializer (/node_modules/twilio/lib/index.js:18:12)

When I removed the 'toLowerCase' method from the generate.js file it worked.
Any solution for this problem?

**Comment by westy92** [comment]
The referenced PR has been merged.  Can this issue be closed?
