### ISSUE TITLE
Issue with library q, nodeback is not a function

### ISSUE THREAD

**Issue by hemc4** [twilio/twilio-node#165]
I am just testing the sample send SMS code. I installed Twilio by putting following line in package.json 

```
"dependencies": {
    "twilio" :"*"
  },
```

```
Hemendras-MacBook-Pro:ref hemc$ node sms.js
/Users/hemc/node-ex/ref/node_modules/q/q.js:126
                    throw e;
                    ^

TypeError: nodeback is not a function
    at /Users/hemc/node-ex/ref/node_modules/q/q.js:1920:17
    at flush (/Users/hemc/node-ex/ref/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

**Comment by Jacke** [comment]
Same error

**Comment by Jacke** [comment]
In my case i've not upgraded my account, so i cant use call function. Sms sending works for me.

**Comment by dkundel** [comment]
Could you show how you are trying to send the SMS?

**Comment by spenceps** [comment]
I'm was having this same issue when I was using the callback method. When I switched to using promises the problem went away.
```javascript
//didn't work
     twilioClient.sendMessage(params, {
        success: function(httpResponse) {
            console.log(httpResponse);
        },
        error: function(httpResponse) {
            console.log("twilio error");
            console.log(httpResponse);
        }
    });

//worked
var twilioPromise = twilioClient.sendMessage(params);
twilioPromise.then(function(message) {
        console.log("twillio sent");
        console.log(message);
    }, function(error){
        console.log("twilio error");
        console.log(error);
    });

```

**Comment by jingming** [comment]
@hemc4 We have just published a update the library. Please give it a shot there and let us know if you are still seeing issues.
