### ISSUE TITLE
Twilio Version 3.0.0-rc.11 Cannot read property 'ConversationsGrant' of undefined

### ISSUE THREAD

**Issue by arvi** [twilio/twilio-node#188]
**Version:** Twilio Version 3.0.0-rc.11
**API Subdomain (api/taskrouter/ip_messaging):** AccessToken
### Code Snippet

``` javascript
/*
Load Twilio configuration from .env config file - the following environment
variables should be set:
process.env.TWILIO_ACCOUNT_SID
process.env.TWILIO_API_KEY
process.env.TWILIO_API_SECRET
process.env.TWILIO_CONFIGURATION_SID
*/
require('dotenv').load();
var http = require('http');
var path = require('path');
var AccessToken = require('twilio').AccessToken;
var ConversationsGrant = AccessToken.ConversationsGrant;
var express = require('express');
var randomUsername = require('./randos');

// Create Express webapp
var app = express();
app.use(express.static(path.join(__dirname, 'public')));

/*
Generate an Access Token for a chat application user - it generates a random
username for the client requesting a token, and takes a device ID as a query
parameter.
*/
app.get('/token', function(request, response) {
    var identity = randomUsername();

    // Create an access token which we will sign and return to the client,
    // containing the grant we just created
    var token = new AccessToken(
        process.env.TWILIO_ACCOUNT_SID,
        process.env.TWILIO_API_KEY,
        process.env.TWILIO_API_SECRET
    );

    // Assign the generated identity to the token
    token.identity = identity;

    //grant the access token Twilio Video capabilities
    var grant = new ConversationsGrant();
    grant.configurationProfileSid = process.env.TWILIO_CONFIGURATION_SID;
    token.addGrant(grant);

    // Serialize the token to a JWT string and include it in a JSON response
    response.send({
        identity: identity,
        token: token.toJwt()
    });
});

// Create http server and run it
var server = http.createServer(app);
var port = process.env.PORT || 3000;
server.listen(port, function() {
    console.log('Express server running on *:' + port);
});

```
### Exception / Log

```
/index.js:13
var ConversationsGrant = AccessToken.ConversationsGrant;
                                    ^

TypeError: Cannot read property 'ConversationsGrant' of undefined
    at Object.<anonymous> (/home/username/Projects/twilio-video-tutorial/video-quickstart-node-master/index.js:13:37)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```
### Steps to Reproduce
1. git clone https://github.com/TwilioDevEd/video-quickstart-node.git
2. npm install
3. node .

However, if I specifically mention in package.json to use `"twilio": "3.0.0-rc.9"` instead of `"twilio": "^3.0.0-edge"`, the video call will work as expected.

**Comment by simonlinj** [comment]
+1 

I can confirm this issue

**Comment by dkundel** [comment]
Hey @arvi and @simonlinj.

The version `3.0.0-rc.11` contains a restructuring of the library that isn't backwards compatible. As you mentioned the versions `3.0.0-rc.9` and `3.0.0-rc.9` will work. You can use those versions or alternatively modify the line:
```js
var AccessToken = require('twilio').AccessToken;
```
to be:
```js
var AccessToken = require('twilio').jwt.AccessToken;
```
Which should also work. I'll raise this issue to the team. Let me know if there are any more issues.

Thanks a lot!

**Comment by arvi** [comment]
Hello @dkundel @simonlinj 

I replaced package.json's twilio line with this `"twilio": "^3.3.1-edge"` and it solved the issue.

I'm having a different issue now regarding media constraints wherein if video is set to false, the webcam is still showing up. I only wanted audio. I'll open a new issue if I can't figure it out. Thanks :smile:

**Comment by jingming** [comment]
We have reinstated the `ConversationsGrant` (note that it is deprecated) for the GA release of the `3.x.x.` line of the library.
