### ISSUE TITLE
Unable to create Role when using twilio-node library

### ISSUE THREAD

**Issue by vinitdave27** [twilio/twilio-node#190]
_Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!_

**Version:2.9.2**
**API Subdomain (api/taskrouter/ip_messaging): ip_messaging**
### Code Snippet

  twilioIPService.roles.create({friendlyName: 'Service_Bot', permission: 'createChannel', permission: 'joinChannel'}).then(function(response) {
    console.log(response);
    twilio_user_role = response.sid;
  }).fail(function(error) {
    console.log(error);
  });
### Exception / Log

TypeError: twilioIPService.roles.create is not a function
    at /home/ubuntu/workspace/app.js:977:25
    at Layer.handle [as handle_request](/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/workspace/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/ubuntu/workspace/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/workspace/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/home/ubuntu/workspace/node_modules/express/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:77:13)
events.js:141
      throw er; // Unhandled 'error' event
### Steps to Reproduce
1. Works when using twilio-php-helper library
2. Does not work for twilio-node library
   3.
### Feature Request

_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by MarwaAbuEssa** [comment]
@vinitdave27 i have the same issue ,  did you found a solution ??? 
regards,

**Comment by jingming** [comment]
We have updated the library that supports role creation: https://github.com/twilio/twilio-node/blob/master/lib/rest/chat/v2/service/role.js#L65
