### ISSUE TITLE
TypeError when record set to true

### ISSUE THREAD

**Issue by niallel** [twilio/twilio-node#271]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:** 3.4.0
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```javascript
// other options omitted, setting record to true causes the problem
twilioClient.calls.create({record: true,})
```

### Exception / Log
```
_http_outgoing.js:458
    throw new TypeError('First argument must be a string or Buffer');
    ^

TypeError: First argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:458:11)
    at Request.write (/fuelservice/node_modules/request/request.js:1514:27)
    at FormData.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:96:13)
    at FormData.emit (events.js:188:7)
    at FormData.CombinedStream.write (/fuelservice/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/fuelservice/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/fuelservice/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/fuelservice/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/fuelservice/node_modules/combined-stream/lib/combined_stream.js:79:10)
```

### Steps to Reproduce
1. Create a call with record set to true as in the code snippet
2. You get the TypeError above
3. Works if true is changed to a string - true.toString()

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by efossier** [comment]
@niallel This should be fixed in our latest release: 3.5.0 and 3.5.0-alpha1. Please let us know if you still have issues!
