### ISSUE TITLE
error in my node.js code ,

### ISSUE THREAD

**Issue by FrancisJebarson** [twilio/twilio-node#328]
This my code is:

var accountSid = 'ACb5ad256ad0f0257b6247cecaf3b98664'; // Your Account SID from www.twilio.com/console
var authToken = 'c10f23e53564872cdfbac63d47eb1f84';  // Your Auth Token from www.twilio.com/console

var twilio = require('twilio');
var client = new twilio(accountSid, authToken);

client.messages.create(
  {
    to: '7xxxxxxxx',
    from: '7eeeeeeee ',
    body: 'This is the ship that made the Kessel Run in fourteen parsecs?',
  },
  (err, message) => {
    console.log(message.sid);
  }
);
I have this exception
Error: username is required
    at new Twilio (E:\seed-project\node_modules\twilio\lib\rest\Twilio.js:128:11)
    at initializer (E:\seed-project\node_modules\twilio\lib\index.js:9:10)
    at Object.<anonymous> (E:\seed-project\send-sms.js:4:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
PS E:\seed-project>

if u resolve this code i will be happy..

**Comment by jingming** [comment]
@FrancisJebarson, thanks for bringing this to our attention!

While we want to get this resolved as soon as possible, I want to point out that this is a public forum and that you should not paste your `auth_token` here. For now, I've edited this post to redact the token. We recommend that you rotate this token as it may have been compromised. 

For questions like this, we recommend that you reach out to help@twilio.com. We have a great support team that would be happy to help you!
