### ISSUE TITLE
SyntaxError: Unexpected token const

### ISSUE THREAD

**Issue by FrancisJebarson** [twilio/twilio-node#329]
**Version:*v8.10.0*
node js code:
const accountSid=process.env.TWILIO_ACCOUNT_SID,
const authToken=process.env.TWILIO_AUTH_TOKEN;
const client = require('twilio')(accountSid,authToken);
client.messages.create(
  {
    to: process.env.TWILIO_PHONE_NUMBER',                      
    from: '+12672146134' ,
    body: 'hiii dudeee'
  },function(err,message){
  	if(err){
  		console.error(err.message);
  	}
  }

);

while running  this above code i have  an error like this .. kindly help me to solve is error..

E:\seed-project>node sms.js
E:\seed-project\sms.js:2
        const authToken=process.env.TWILIO_AUTH_TOKEN;
        ^^^^^
SyntaxError: Unexpected token const
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by dkundel** [comment]
You have a comma instead of a ; after `TWILIO_ACCOUNT_SID`.
Change that and the code should work.

Cheers,
Dominik

**Comment by akanksha4715** [comment]
Lol, I did the same mistake. Now, I am laughing at myself.
