### ISSUE TITLE
Twilio require('twilio') error

### ISSUE THREAD

**Issue by imsabarinath** [twilio/twilio-node#352]
I was trying to set up twilio but stuck with the following error on require('twilio') module.

`SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Wamp\www\Projects\HR3\node_modules\twilio\lib\rest\accounts\v1\credential\aws.js:12:9)
(node:7768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

I am using the latest version of twilio 3.17.1. My Node version is 9.3.0

**Comment by imsabarinath** [comment]
Issue seems to be with q.js file being corrupt.
