### ISSUE TITLE
calls(...).recordings.create is not a function

### ISSUE THREAD

**Issue by p8952** [twilio/twilio-node#396]
**Version:** 3.6.3 (Twilio Functions: https://www.twilio.com/docs/runtime/functions/packages)

### Code Snippet
```node
exports.handler = function(context, event, callback) {    
    const authToken  = '<REDACTED>';
    const accountSid = event.AccountSid;
    const callSid    = event.CallSid;
    
    const twilioClient = require('twilio')(accountSid, authToken);

    twilioClient.calls(callSid)
        .recordings
        .create()
        .then((recording) => {
            console.log('Recording: ', recording.sid);
        })
        .done();
};
```

### Exception/Log
```
Execution Started

{ message: 'twilioClient.calls(...).recordings.create is not a function',
  name: 'TypeError',
  stack: 'TypeError: twilioClient.calls(...).recordings.create is not a function\n    at Object.exports.handler (/var/task/handlers/ZF0c245fe6b5f18af10261e8a70a33ae2b.js:13:10)\n    at Object.exports.handler (/var/task/node_modules/enigma-lambda/index.js:306:10)\n    at exports.handler (/var/task/enigma.js:17:9)' }


Execution Ended in 190.14ms using 58MB
```

### Steps to Reproduce
1. Create a new Twilio function
2. Paste in the above Code Snippet
3. Replace `<REDACTED>` with your authToken
4. Point a Twilio number at the Twilio function
5. Call the Twilio number

**Comment by imthepitts** [comment]
Hi @p8952, 

Sorry you're having trouble. Please update your Twilio package to the latest version (3.24.0) and retry. The feature you're using is fairly new and not included in 3.6.3.

All the Best,
Zack
