### ISSUE TITLE
Error: username is required

### ISSUE THREAD

**Issue by TriplexRoss** [twilio/twilio-node#398]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:** 3.24.0

### Code Snippet
```node
var twilio = new Twilio(SID,TOKEN);
```

### Exception/Log
```
Error: username is required
    at new Twilio (/home/spaceboyross/OS.js-apps/twilio-client/node_modules/twilio/lib/rest/Twilio.js:137:11)
    at new initializer (/home/spaceboyross/OS.js-apps/twilio-client/node_modules/twilio/lib/index.js:9:10)
    at core.app.post (/home/spaceboyross/OS.js-apps/twilio-client/server.js:7:13)
    at Layer.handle [as handle_request] (/home/spaceboyross/OS.js/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/spaceboyross/OS.js/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/spaceboyross/OS.js/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/spaceboyross/OS.js/node_modules/express/lib/router/layer.js:95:5)
    at /home/spaceboyross/OS.js/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/spaceboyross/OS.js/node_modules/express/lib/router/index.js:335:12)
    at next (/home/spaceboyross/OS.js/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/spaceboyross/OS.js/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/home/spaceboyross/OS.js/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/spaceboyross/OS.js/node_modules/express/lib/router/index.js:317:13)
    at /home/spaceboyross/OS.js/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/spaceboyross/OS.js/node_modules/express/lib/router/index.js:335:12)
    at next (/home/spaceboyross/OS.js/node_modules/express/lib/router/index.js:275:10)
```

### Steps to Reproduce
1. Attempt to login

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by imthepitts** [comment]
Hi @SpaceboyRoss01,

Sorry you're having trouble. Looks like your `SID` is either null or empty string. It's just a simple validation check:

https://github.com/twilio/twilio-node/blob/6283ca3016be05e9355499cfb58b76abb827fe78/lib/rest/Twilio.js#L136-L138

Please verify the input and if you continue having trouble, post a complete code snippet that reproduces the issue.

Zack

**Comment by SpaceboyRoss01** [comment]
It's a constant value that I set in the file.27.11.2018, 08:49, "Zack Pitts" <notifications@github.com>:Hi @SpaceboyRoss01,
Sorry you're having trouble. Looks like your SID is either null or empty string. It's just a simple validation check:
https://github.com/twilio/twilio-node/blob/6283ca3016be05e9355499cfb58b76abb827fe78/lib/rest/Twilio.js#L136-L138
Please verify the input and if you continue having trouble, post a complete code snippet that reproduces the issue.
Zack

**Comment by IdamEniIdam** [comment]
/home/idam/Desktop/proximity/proximity/functions/verify_one_time_password.js
  23:9  warning  Avoid nesting promises  promise/no-nesting
  23:9  warning  Avoid nesting promises  promise/no-nesting

✖ 2 problems (0 errors, 2 warnings)

✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...

Error: Server Error. getaddrinfo ENOTFOUND servicemanagement.googleapis.com servicemanagement.googleapis.com:443
idam@idam:~/Desktop/proximity/proximity$ firebase deploy --project proximity-be8f9

Error: Server Error. Client network socket disconnected before secure TLS connection was established
idam@idam:~/Desktop/proximity/proximity$ firebase deploy --project proximity-be8f9

=== Deploying to 'proximity-be8f9'...

i  deploying functions
Running command: npm --prefix "functions" run lint

> functions@ lint /home/idam/Desktop/proximity/proximity/functions
> eslint .


/home/idam/Desktop/proximity/proximity/functions/verify_one_time_password.js
  23:9  warning  Avoid nesting promises  promise/no-nesting
  23:9  warning  Avoid nesting promises  promise/no-nesting

✖ 2 problems (0 errors, 2 warnings)

✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: username is required
    at new Twilio (/home/idam/Desktop/proximity/proximity/functions/node_modules/twilio/lib/rest/Twilio.js:100:11)
    at Object.<anonymous> (/home/idam/Desktop/proximity/proximity/functions/twilio.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/idam/Desktop/proximity/proximity/functions/request_one_time_password.js:2:16)

Having trouble? Try firebase deploy --help

Having similar issue please any help

**Comment by childish-sambino** [comment]
This doesn't appear to be a bug. Please check the [Twilio Support Help Center](https://support.twilio.com) and [file a support ticket](https://twilio.com/help/contact) if you don't find an answer to your question.

**Comment by Shree2470** [comment]
Can you pleas tell me the solution for  this error "throw new Error('username is required');"

**Comment by childish-sambino** [comment]
@Shree2470 Please open a new issue as closed issues are not tracked as closely.
