### ISSUE TITLE
Cannot find module './_stream_duplex'

### ISSUE THREAD

**Issue by edgework** [twilio/twilio-node#430]
All of a sudden ALL of our servers that ran the Twilio module blew up with the following stack trace.   Nothing special happened there's no other indications of problems.  45 servers all at almost the same millisecond.  What is going on??

**Version:**

3.29.2

### Exception/Log
```
ERROR: Cannot find module './_stream_duplex'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at BufferList.Readable (/opt/agent/server/node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js:128:22)
    at BufferList.Duplex (/opt/agent/server/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:43:12)
    at new BufferList (/opt/agent/server/node_modules/bl/bl.js:32:16)
    at BufferList (/opt/agent/server/node_modules/bl/bl.js:7:12)
    at Request.readResponseBody (/opt/agent/server/node_modules/twilio/node_modules/request/request.js:992:16)
    at Request.onRequestResponse (/opt/agent/server/node_modules/twilio/node_modules/request/request.js:973:12)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13) 
```

### Steps to Reproduce
1.  ?

**Comment by edgework** [comment]
Sorry wrong version. This is happening with 3.26.1.   This is on servers that have been running unchanged for many weeks.  Only recently has this started happening indicating some change in the network protocol.

**Comment by childish-sambino** [comment]
Internal ticket suggests some version mismatches between hosts and processes. Closing.
