### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type boolean

### ISSUE THREAD

**Issue by peterb0yd** [twilio/twilio-node#431]
So I have narrowed it down to `express`. If I run the script below inside the node console, it works perfectly. However, when I run it over `express`, the error happens. 

**Version: 3.29.2**
**Node version:  11.12.0**
**NPM version:  6.7.0**

### Code Snippet
```node
const twilio = require('twilio');
const {ssid, auth, mainNumber} = require('../config'); 
const client = twilio(ssid, auth);

const getClient = ({client, mainNumber})=> {
    return {
        sendText: async function ({phone, msg}) {
            try { 
                return await client.messages.create({
                    to: phone,
                    from: mainNumber,
                    body: msg
                });
            } catch (error) {
                throw error;
            }
        }
    };
}

const phoneClient = getClient({
    client, 
    mainNumber
});

phoneClient.sendText({ phone: '######', msg: 'Hey!' });
```

### Exception/Log
```
_http_outgoing.js:607
    throw new ERR_INVALID_ARG_TYPE('first argument',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type boolean
    at write_ (_http_outgoing.js:607:11)
    at ClientRequest.write (_http_outgoing.js:579:10)
    at Request.write (/home/peter/TopRock Labs/API/node_modules/request/request.js:1500:27)
    at FormData.ondata (internal/streams/legacy.js:15:31)
    at FormData.emit (events.js:197:13)
    at FormData.EventEmitter.emit (domain.js:446:20)
    at FormData.CombinedStream.write (/home/peter/TopRock Labs/API/node_modules/combined-stream/lib/combined_stream.js:119:8)
    at FormData.CombinedStream._pipeNext (/home/peter/TopRock Labs/API/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/home/peter/TopRock Labs/API/node_modules/combined-stream/lib/combined_stream.js:80:10)
    at FormData.CombinedStream._pipeNext (/home/peter/TopRock Labs/API/node_modules/combined-stream/lib/combined_stream.js:108:8)
```

### Steps to Reproduce
1. Run file inside of an express app
2. Try to execute the `sendText` function from one of the express routes

No idea what this error is about. At a complete loss.

**Comment by peterb0yd** [comment]
Any ideas anyone? The only work-around we found is to downgrade to a 2.X version and stop using 3.X

**Comment by peterb0yd** [comment]
* FIXED * 

I'll be surprised if anyone has this error, but it was completely my fault. 

In another section of my code, completely unrelated to twilio, I had added a prototype function to the Array, String, Object, and Number classes. This is highly not recommended in general, but in this case it was somehow interfering with the twilio-node library and causing the Node process to crash.

Carry on!
