### ISSUE TITLE
ESOCKETTIMEDOUT after upgrading to 3.29.2

### ISSUE THREAD

**Issue by tapz** [twilio/twilio-node#432]
When upgrading from 3.29.1 to 3.29.2 I started getting SOCKETTIMEDOUT. I'm using a test account sid.

**Version:**
3.29.2

### Code Snippet
```node
const twilio = require('twilio')(config.smsProvider.accountSid, config.smsProvider.authToken);
twilio.messages.create({
      to: phoneNumber,
      from: ''Mysenderid,
      body: message,
      statusCallback: config.smsProvider.callbackUrl
    }, (err, msg) => {
```

### Exception/Log
```node
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Users/tapani/projects/XXX/xxx-backend/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at TLSSocket.emitTimeout (_http_client.js:721:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

### Steps to Reproduce
1. Create message (send)

**Comment by childish-sambino** [comment]
Details on test credentials: https://www.twilio.com/docs/iam/test-credentials

In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).

**Comment by tapz** [comment]
I have filed a support ticket. And btw it still does not work. Probably a conflict with the http library versions.

**Comment by childish-sambino** [comment]
The `request` lib was upgraded as part of that release.
