### ISSUE TITLE
Required parameter "opts.identity" missing

### ISSUE THREAD

**Issue by jfbaquerocelis** [twilio/twilio-node#511]
Hello :smiley: I've an error in my code but I don't know why it appears.

**Version:** 3.37.1

### Code Snippet
```node
const { Twilio: { accountSid, authToken, serviceSid } } = require('../../config')
const twilio = require('twilio')

async function createBinding (msg, reply) {
  try {
    const client = twilio(accountSid, authToken)
    const service = client.notify.services(serviceSid)
    const options = {
      identity: msg.binding.Identity,
      bindingType: msg.binding.BindingType,
      address: msg.binding.Address,
      tag: msg.binding.Tag
    }
    // Creamos el binding
    const bindingSuccess = await service.bindings.create(options)

    reply(null, bindingSuccess)
  } catch (err) {
    reply(err, null)
  }
}

module.exports = createBinding
```

### Exception/Log
```
Error: Required parameter "opts.identity" missing.
    at Function.create (/myproject/node_modules/twilio/lib/rest/notify/v1/service/binding.js:76:13)
    at Seneca.createBinding (/myproject/consultations/actions/createBinding.js:16:49)
    at Object.execute_action (/myproject/node_modules/seneca/lib/act.js:342:17)
    at Object.act_fn [as fn] (/myproject/node_modules/seneca/lib/act.js:62:16)
    at Immediate.processor [as _onImmediate] (/myproject/node_modules/gate-executor/gate-executor.js:131:14)
    at processImmediate (internal/timers.js:439:21)
```

### Steps to Reproduce
1. I receive the binding info from a mobile application Android:
```
binding data {
  Address: 'fEk_fgxS93w:APA91bGYfUhEcgAh6dF2ygf0vn_OjMCY2er4no5xzovTIUiCavZ99ZD9yUNbNkX4NUhJmxgRDVf0uLKs6ajAd0quC0ofm0NysZfDrcdryX-llIKrpli8Ki3j4eZOnvJ76L6luX5LP8Xg',
  BindingType: 'fcm',
  Endpoint: '123@fEk_fgxS93w',
  Identity: 'professional123',
  Tag: [ 'video' ]
}


``` 
2. But when I pass it to method **.create()**, the error above appears

I hope that you can help me! Regards!

**Comment by childish-sambino** [comment]
I'm not seeing anything to indicate what's going wrong here. Can you try logging the contents of `options` (and `msg`) before calling `create`?

**Comment by jfbaquerocelis** [comment]
Hi @childish-sambino thanks for your response! When I'm going to show the output that you request me, I can see that the mobile application sent me 2 request to my endpoint and inside one the values come `undefined`.

Thanks for your help and sorry for wasting your time! :pray: :+1: :smiley:
