### ISSUE TITLE
Exceptions thrown from (verify) REST API have undefined .stack

### ISSUE THREAD

**Issue by GeoffWilliams** [twilio/twilio-node#548]
**Overview**

Exceptions thrown from (`verify`) REST API have undefined `.stack`.

**Motivation**

Exceptions returned from the Twilio API during (`verify` and maybe other) REST calls have an undefined `.stack` property so its impossible to identify the calling code from the exception alone. This is a problem as non-trivial apps could make many different calls to the Twilio API with many different parameter sets, increasing time and difficulty of fixing customer code.

**twilio-node Version**

```
$ npm ls twilio
twilo_exception_handling_testcase@1.0.0 /home/geoff/tmp/twilo_exception_handling_testcase
└── twilio@3.41.1 
```

**Operating System**

_Probably not relevant_

```shell
$ node --version
v12.14.0
$ uname -a
Linux computer 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Reproduction**

Running the following code snipit with the `node` command demonstrates the missing `.stack` property. To help reproduce this for debugging I've created a git repository: https://github.com/GeoffWilliams/twilo_exception_handling_testcase

1. `node index.js`
2. load http://localhost:3000 in web browser
3. check output in console:
  1. value of `e.stack` is `undefined`
  2. output of `console.trace` is not useful (as expected)

```javscript
const asyncHandler = require('express-async-handler');

const express = require('express');
const app = express();
const port = 3000;

const accountSid = process.env.TWILIO_ACCOUNT_SID || "hardcodefortesting";
const authToken = process.env.TWILIO_AUTH_TOKEN ||  "hardcodefortesting";
const twilioVerifySid = process.env.TWILIO_VERIFY_SID || "hardcodefortesting";

app.listen(port, () => console.log(`Example app listening on port ${port}!`));

const t = {
    async callTwilio() {
        // creating the client with wrong credentials preserves the stack
        const client = require('twilio')(accountSid, authToken);
        const preservedStack = new Error("preserved caller stack");
        const _ = await client.verify.services(twilioVerifySid).verifications.create({
            to:  Math.random(),
            channel: "sms"
        }).then(verification => {
            console.log("this will never be reached since we trigger exception");
        }).catch(e => {
            console.trace("value of e.stack (and also our own stack)----> " + e.stack);
            throw preservedStack;
        });
        log.debug("returning normally");
    }
};

const runner = {
    async wrap() {
        await t.callTwilio();
    }
};

app.get('/', asyncHandler(async (req, res, next) => {
    const result = await runner.wrap();
    res.send(result);
}));


// error handler
app.use(function(err, req, res, next) {
    console.error(err);

    res.status(err.status || 500);
    res.send(err.stack);
});
```

_Sample output_

```
$ node index.js 
Example app listening on port 3000!
Trace: value of e.stack (and also our own stack)----> undefined
    at /home/geoff/tmp/twilo_exception_handling_testcase/index.js:24:21
    at Promise_then_rejected (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/q/q.js:779:43)
    at Promise_done_rejected (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/q/q.js:861:26)
    at Rejected_then [as then] (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/q/q.js:1323:23)
    at Rejected_dispatch [as dispatch] (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/q/q.js:1311:23)
    at Pending_become_eachMessage_task (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/q/q.js:1369:30)
    at RawTask.call (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/asap/asap.js:40:19)
    at flush (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Error: preserved caller stack
    at Object.callTwilio (/home/geoff/tmp/twilo_exception_handling_testcase/index.js:17:32)
    at Object.wrap (/home/geoff/tmp/twilo_exception_handling_testcase/index.js:33:17)
    at /home/geoff/tmp/twilo_exception_handling_testcase/index.js:38:33
    at asyncUtilWrap (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/express-async-handler/index.js:3:20)
    at Layer.handle [as handle_request] (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/express/lib/router/layer.js:95:5)
    at /home/geoff/tmp/twilo_exception_handling_testcase/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/geoff/tmp/twilo_exception_handling_testcase/node_modules/express/lib/router/index.js:335:12)

```

**Related Issues**

Might have been touched as part of https://github.com/twilio/twilio-node/issues/83

**Suggest a Fix**

Please include the calling stack in all Errors.

**Workaround**

The testcase demonstrates an ugly workaround:

1. Save the present stack before calling Twilio API
2. Catch errors thrown by while using API
3. Throw the saved callstack instead of the Exception from Twilio (massaging values as required).

This is demonstrated working in the sample output, above

**Comment by childish-sambino** [comment]
Looks like a bug to me. This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by harelkh** [comment]
is there a solution? i get :
      username: token.username,
                      ^

TypeError: Cannot read property 'username' of undefined
    at /home/ubuntu/powowsChat/bin/www:104:23
    at Promise_done_rejected (/home/ubuntu/powowsChat/node_modules/q/q.js:861:26)
    at Rejected_then [as then] (/home/ubuntu/powowsChat/node_modules/q/q.js:1323:23)
    at Rejected_dispatch [as dispatch] (/home/ubuntu/powowsChat/node_modules/q/q.js:1311:23)
    at Pending_become_eachMessage_task (/home/ubuntu/powowsChat/node_modules/q/q.js:1369:30)
    at RawTask.call (/home/ubuntu/powowsChat/node_modules/asap/asap.js:40:19)
    at flush (/home/ubuntu/powowsChat/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by childish-sambino** [comment]
@harelkh Your issue does not look related. Could you file a separate ticket and include a code sample illustrating this issue?
