### ISSUE TITLE
Unexpected token U in JSON

### ISSUE THREAD

**Issue by meness** [twilio/twilio-node#570]
### Issue Summary
It throws an unhandled exception.

### Code Snippet
```node
const twilio = require('twilio')(sid, token);

exports.send = async (to, body) => {
  return twilio.messages.create({
    from: number,
    to,
    body,
  });
};
```

### Exception/Log
```
(node:3376) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token U in JSON at position 4
    at JSON.parse (<anonymous>)
    at new RestException (C:\Users\Alireza\Desktop\X\node_modules\twilio\lib\base\RestException.js:7:59)
    at success (C:\Users\Alireza\Desktop\X\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alireza\Desktop\X\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alireza\Desktop\X\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alireza\Desktop\X\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alireza\Desktop\X\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alireza\Desktop\X\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alireza\Desktop\X\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

### Technical details:
* twilio-node version: 3.43.0
* node version: 12.10.0

**Comment by childish-sambino** [comment]
I've not been able to recreate this issue. Are you using a custom HTTP client?

**Comment by meness** [comment]
I'm using Axios, but it should not cause a conflict. I tried to wrap Twilio client with a `try/catch` but it still throws the exception. I checked your codes and found you didn't use `async` keyword for the method mentioned in the error, so no one can handle exceptions occur inside of your codes.

**Comment by childish-sambino** [comment]
We recently migrated this library to use `axios` as well so that may be causing an issue, but I'm not able to pin it down. Are you able to share a small example with a custom client that is still breaking?

Regarding catching exceptions, `create` returns a promise so you can either `await` the result and catch exceptions or use `.then(..).catch(...)`.

**Comment by meness** [comment]
@childish-sambino I debugged Twilio, and found the real error is `451 Unavailable For Legal Reasons`. What's that? I'm sending SMS to a number from Iran (+98xxxxxxxxxx).

**Comment by childish-sambino** [comment]
Maybe check here: https://support.twilio.com/hc/en-us/articles/223181108-How-International-SMS-Permissions-work

**Comment by meness** [comment]
@childish-sambino Do you mean geo permissions? If yes, all options are already enabled in the console. If not, please clarify.

**Comment by childish-sambino** [comment]
Could be because certain countries/regions are blocked based on US foreign policy and national security goals. Best to open a [support ticket](https://support.twilio.com) for further details and/or debugging as this is not a client library issue.

**Comment by woxman** [comment]
you finded solution for this problem?

**Comment by childish-sambino** [comment]
@woxman Please open a new issue as closed issues are not tracked as closely.
