### ISSUE TITLE
Wrong validation on accountSid when using API Sid/Api Key to initialize the client

### ISSUE THREAD

**Issue by vence722** [twilio/twilio-node#600]
# Issue Summary
When initialize the client using API Sid/Key, validation still applied to the username field which will check if the field starts with 'AC'. But API Sid should start with 'SK'.

### Steps to Reproduce
Initialize the twilio SDK client using API Sid/Key

### Code Snippet
```node
import twilio from 'twilio'
twilio(apiSid, apiKey)
```

### Exception/Log
```
Error: accountSid must start with AC
    at new Twilio (/var/task/node_modules/twilio/lib/rest/Twilio.js:137:11)
    at Object.initializer [as default] (/var/task/node_modules/twilio/lib/index.js:9:10)
    at new Twilio (/var/task/src/services/twilio.js:9:39)
    at initTwilio (/var/task/src/controllers/sms.js:19:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.sendVerification (/var/task/src/controllers/sms.js:49:28)
```

### Technical details:
* twilio-node version: 3.48.0
* node version: 13.12.0

**Comment by childish-sambino** [comment]
This is similar to https://github.com/twilio/twilio-csharp/issues/531, but the Node lib is also expecting an account SID in this case.

The fix is to include the account SID in optional params. E.g.:
```js
twilio(apiSid, apiKey, { accountSid });
```

**Comment by vence722** [comment]
@childish-sambino Yes, this is my work-around too. I can even use a dummy value of accountSid to bypass the validation. E.g.:
```
twilio(apiSid, apiKey, { accountSid: 'AC' })
```
However, I still get a feeling that this is a bug in the twilio node library, as the document mentions that `twilio()` function could accept both accountSid/accountSecret and apiSid/apiKey pairs. Hope this could get fixed in the future version. Thank you!

**Comment by childish-sambino** [comment]
Probably need a similar implementation here as https://github.com/twilio/twilio-csharp/pull/533

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by ducsuus** [comment]
I believe this is an important issue to address, even if just to update the error message thrown to explain the different requirements for API Keys.

At present, I understand that this behaviour is not described in the documentation. Because the error thrown suggests that API Keys cannot be used instead of account auth tokens, developers are encouraged to avoid using API Keys, which is poor practice.

If the account SID begins with "SK", a different error message could be provided:

`accountSid must start with AC. The SID provided indicates an API Key, which requires the accountSid to be passed as one of the options in the third parameter: {accountSid: "ACXXX}`

**Comment by rohanmathewalex** [comment]
`2021-01-21T12:09:44.457285+00:00 app[web.1]: 
2021-01-21T12:09:44.457303+00:00 app[web.1]: > hardcore-whatsapp@0.0.0 start /app
2021-01-21T12:09:44.457303+00:00 app[web.1]: > node ./bin/www
2021-01-21T12:09:44.457304+00:00 app[web.1]: 
2021-01-21T12:09:44.988266+00:00 app[web.1]: /app/node_modules/twilio/lib/rest/Twilio.js:140
2021-01-21T12:09:44.988280+00:00 app[web.1]:     throw new Error('accountSid must start with AC');
2021-01-21T12:09:44.988281+00:00 app[web.1]:     ^
2021-01-21T12:09:44.988282+00:00 app[web.1]: 
2021-01-21T12:09:44.988282+00:00 app[web.1]: Error: accountSid must start with AC
2021-01-21T12:09:44.988283+00:00 app[web.1]:     at new Twilio (/app/node_modules/twilio/lib/rest/Twilio.js:140:11)
2021-01-21T12:09:44.988284+00:00 app[web.1]:     at initializer (/app/node_modules/twilio/lib/index.js:9:10)
2021-01-21T12:09:44.988284+00:00 app[web.1]:     at Object.<anonymous> (/app/helpers/user-helper.js:5:33)
2021-01-21T12:09:44.988285+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-01-21T12:09:44.988285+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-01-21T12:09:44.988285+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-01-21T12:09:44.988286+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-01-21T12:09:44.988286+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-01-21T12:09:44.988286+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-01-21T12:09:44.988287+00:00 app[web.1]:     at Object.<anonymous> (/app/routes/users.js:3:20)
2021-01-21T12:09:45.001711+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-01-21T12:09:45.001965+00:00 app[web.1]: npm ERR! errno 1
2021-01-21T12:09:45.006786+00:00 app[web.1]: npm ERR! hardcore-whatsapp@0.0.0 start: `node ./bin/www`
2021-01-21T12:09:45.006883+00:00 app[web.1]: npm ERR! Exit status 1
2021-01-21T12:09:45.006997+00:00 app[web.1]: npm ERR! 
2021-01-21T12:09:45.007084+00:00 app[web.1]: npm ERR! Failed at the hardcore-whatsapp@0.0.0 start script.
2021-01-21T12:09:45.007173+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-01-21T12:09:45.015485+00:00 app[web.1]: 
2021-01-21T12:09:45.015632+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-01-21T12:09:45.015720+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-01-21T12_09_45_007Z-debug.log
2021-01-21T12:09:45.089679+00:00 heroku[web.1]: State changed from starting to crashed
2021-01-21T12:09:45.056816+00:00 heroku[web.1]: Process exited with status 1
2021-01-21T12:31:31.720137+00:00 heroku[web.1]: State changed from crashed to starting
2021-01-21T12:31:43.265966+00:00 heroku[web.1]: Starting process with command `npm start`
2021-01-21T12:31:47.056171+00:00 app[web.1]: 
2021-01-21T12:31:47.056186+00:00 app[web.1]: > hardcore-whatsapp@0.0.0 start /app
2021-01-21T12:31:47.056186+00:00 app[web.1]: > node ./bin/www
2021-01-21T12:31:47.056187+00:00 app[web.1]: 
2021-01-21T12:31:48.289098+00:00 app[web.1]: /app/node_modules/twilio/lib/rest/Twilio.js:140
2021-01-21T12:31:48.289156+00:00 app[web.1]:     throw new Error('accountSid must start with AC');
2021-01-21T12:31:48.289157+00:00 app[web.1]:     ^
2021-01-21T12:31:48.289157+00:00 app[web.1]: 
2021-01-21T12:31:48.289158+00:00 app[web.1]: Error: accountSid must start with AC
2021-01-21T12:31:48.289158+00:00 app[web.1]:     at new Twilio (/app/node_modules/twilio/lib/rest/Twilio.js:140:11)
2021-01-21T12:31:48.289159+00:00 app[web.1]:     at initializer (/app/node_modules/twilio/lib/index.js:9:10)
2021-01-21T12:31:48.289159+00:00 app[web.1]:     at Object.<anonymous> (/app/helpers/user-helper.js:5:33)
2021-01-21T12:31:48.289159+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-01-21T12:31:48.289160+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-01-21T12:31:48.289160+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-01-21T12:31:48.289160+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-01-21T12:31:48.289161+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-01-21T12:31:48.289161+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-01-21T12:31:48.289161+00:00 app[web.1]:     at Object.<anonymous> (/app/routes/users.js:3:20)
2021-01-21T12:31:48.353877+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-01-21T12:31:48.366134+00:00 app[web.1]: npm ERR! errno 1
2021-01-21T12:31:48.413004+00:00 app[web.1]: npm ERR! hardcore-whatsapp@0.0.0 start: `node ./bin/www`
2021-01-21T12:31:48.413297+00:00 app[web.1]: npm ERR! Exit status 1
2021-01-21T12:31:48.413388+00:00 app[web.1]: npm ERR! 
2021-01-21T12:31:48.413578+00:00 app[web.1]: npm ERR! Failed at the hardcore-whatsapp@0.0.0 start script.
2021-01-21T12:31:48.413748+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-01-21T12:31:48.439932+00:00 app[web.1]: 
2021-01-21T12:31:48.440138+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-01-21T12:31:48.440224+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-01-21T12_31_48_414Z-debug.log
2021-01-21T12:31:48.514843+00:00 heroku[web.1]: Process exited with status 1
2021-01-21T12:31:48.569054+00:00 heroku[web.1]: State changed from starting to crashed`


I am getting this error while deploying my application to heroku

**Comment by rohanmathewalex** [comment]
`2021-01-21T12:09:44.988266+00:00 app[web.1]: /app/node_modules/twilio/lib/rest/Twilio.js:140
2021-01-21T12:09:44.988280+00:00 app[web.1]:     throw new Error('accountSid must start with AC');
2021-01-21T12:09:44.988281+00:00 app[web.1]:     ^
2021-01-21T12:09:44.988282+00:00 app[web.1]: 
2021-01-21T12:09:44.988282+00:00 app[web.1]: Error: accountSid must start with AC`


I'm receiving this error while deploying my application to heroku

**Comment by shwetha-manvinkurke** [comment]
Hi @rohanmathewalex, 

The error says `accountSid must start with AC`, so I would start by checking the `accountSid` that's being passed to your application. 

Let me know how it goes. Also, code samples help if you can't figure it out.

Thanks,
Shwetha

**Comment by rohanmathewalex** [comment]
> This is similar to [twilio/twilio-csharp#531](https://github.com/twilio/twilio-csharp/issues/531), but the Node lib is also expecting an account SID in this case.
> 
> The fix is to include the account SID in optional params. E.g.:
> 
> ```js
> twilio(apiSid, apiKey, { accountSid });
> ```

I think this is the issue I'm facing. where should i need to place this `twilio(apiSid, apiKey, { accountSid: 'AC' })` on require part?

**Comment by jlcaicedo** [comment]
The solution is very easy, when you should use the Account SID you would verify this account start by AC
