### ISSUE TITLE
Error on Verification Create: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by tomasswood** [twilio/twilio-node#658]
### Issue Summary
I get the following error thrown when running `verifications.create`. No issue running `services.create` and I can see the service in my twilio account.

### Code Snippet
```node
await twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN).verify.services(secret).verifications.create({ to: this.userMobileNumber, channel: 'sms' });
```

### Exception/Log
```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/tomasswood/development/hailer/node_modules/https-proxy-agent/src/agent.ts:27:46)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/tomasswood/development/hailer/node_modules/https-proxy-agent/src/index.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/tomasswood/development/hailer/node_modules/twilio/lib/base/RequestClient.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Technical details:
* twilio-node version: 3.56.0
* node version: 10.21.0

**Comment by shwetha-manvinkurke** [comment]
@tomasswood I could not reproduce the issue you mention. Maybe a problem with the `https-proxy-agent` installation? What's the version of the `https-proxy-agent` that was installed? Would you be able to do a clean install and retry?

**Comment by tomasswood** [comment]
Hi @shwetha-manvinkurke 
I have tried removing node_modules and my yarn.lock completey as well as ensuring the following are installed:

```
"axios": "^0.21.1",
"https-proxy-agent": "^5.0.0",
```

No matter what the exact same issue persists. We are also not defining `HTTP_PROXY` anywhere, although it looks like the issue occurs on import and not when the constructor is called anyway.

**Comment by thinkingserious** [comment]
Hello @tomasswood,

It looks like you may a circular dependency issue. Could you please try utilizing [Madge](https://www.npmjs.com/package/madge) to verify?

With best regards,

Elmer

**Comment by ciekawy** [comment]
I just hit very similar issue in a quite different environment (AWS lambda / `serverless`). Madge showed no circular deps. The `https-proxy-agent` is used by `twilio` and issue seems to be related to `https-proxy-agent` unable to resolve `agent-base` - in my case the workaround seems to be to add `agent-base` to `externals` in `webpack.config.js`.

Writing this as someone may find this helpful.
