### ISSUE TITLE
conference status update

### ISSUE THREAD

**Issue by shahanahmed86** [twilio/twilio-node#663]
### Issue Summary
I was following the blog found on twilio i.e.: https://www.twilio.com/blog/multi-party-calls-voip-gsm-programmable-voice. When a callee hangs up the the call then "/completecall/:session_id" is revoked, but it gives an error "RestException [Error]: Bad request" on the line `await conference.update({ status: 'completed' });`

### Code Snippet
```node
const checkMethod = (req, res, next) => {
	if (!['GET', 'POST'].includes(req.method.toUpperCase())) {
		return res.status(400).send('Invalid method found for the route...');
	}

	return next();
};

router.use('/completeCall/:session_id', checkMethod, async (req, res) => {
	try {
		// getting params/body from request
		const { session_id } = req.params;

		// initialize the twilio client
		console.log(req.method, req.body, session_id_to_conference_sid[session_id]);
		const client = twilioInitiator();
		console.log('one');
		let conference = client.conferences(session_id_to_conference_sid[session_id]);
		console.log('two', conference);
		const participants = await conference.participants.list().then((a) => {
			console.log('list', a);
			return a;
		});

		if (participants.length === 1) {
			console.log('three');
			await conference.update({ status: 'completed' });
			console.log('five');
		}

		return res.send({
			status_code: 200
		});
	} catch (error) {
		console.log('catchError', error);
		return res.send({
			status_code: 400
		});
	}
});
```

### Exception/Log
```node
RestException [Error]: Bad request
    at success (/home/shahan/work/materialy/main/server/node_modules/twilio/lib/base/Version.js:88:15)
    at Promise_then_fulfilled (/home/shahan/work/materialy/main/server/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/home/shahan/work/materialy/main/server/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/home/shahan/work/materialy/main/server/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/home/shahan/work/materialy/main/server/node_modules/q/q.js:1369:30)
    at RawTask.call (/home/shahan/work/materialy/main/server/node_modules/asap/asap.js:40:19)
    at flush (/home/shahan/work/materialy/main/server/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  status: 400,
  code: 20001,
  moreInfo: 'https://www.twilio.com/docs/errors/20001',
  details: undefined
}
```

### Technical details:
* twilio-node version: 3.57.0
* node version: 12.21.0

**Comment by JenniferMah** [comment]
Hi @shahanahmed86 could enable the [debug logs](https://github.com/twilio/twilio-node#enable-debug-logging) and include the results in your reply?

**Comment by cmcaboy** [comment]
@shahanahmed86 I am also running into this issue. What was the resolution? I see this has already been closed out.

**Comment by shahanahmed86** [comment]
> @shahanahmed86 I am also running into this issue. What was the resolution? I see this has already been closed out.

I wanted to implemented on a project but unfortunately the project was cancelled so I didn't reply to @JenniferMah and didn't browse for the solution

**Comment by cmcaboy** [comment]
ok, thank you for the reply. Since this ticket is closed, I opened another one with the logs requested.
