### ISSUE TITLE
Twilio Conference Update throws error

### ISSUE THREAD

**Issue by cmcaboy** [twilio/twilio-node#681]
### Issue Summary
I am trying to end the Twilio conference object, but the SDK throws an ambiguous error.

### Steps to Reproduce
1. Start a conference

```
const twiml = new VoiceResponse()
    const dial = twiml.dial()

    dial.conference(
      {
        statusCallback: `${backendUrl}/twilio/outboundCallBack?from=${from}&to=${req.body.number}&conference_id=${conference_id}`,
        statusCallbackEvent: ['join', 'leave'],
        statusCallbackMethod: 'POST',
        maxParticipants: 5,
        record: 'record-from-start',
        startConferenceOnEnter: true,
      },
      conference_id,
    )
```

2. Have a participant join the call
```
  const create_participant = await client
      .conferences(conference_id)
      .participants.create({
        record: true,
        recordingTrack: can_record ? 'both' : 'outbound',
        from: from,
        to: to,
        timeout: 120,
        recordingStatusCallbackMethod: 'POST',
        recordingStatusCallbackEvent: ['completed', 'in-progress'],
        recordingStatusCallback: `${backendUrl}/twilio/completeCall?conference_id=${conference_id}`,
        endConferenceOnExit: true,
        startConferenceOnEnter: true,
        earlyMedia: false,
      })
```

3. As it is dialing, execute the following code:

```
client.conferences(ConferenceSid).update({ status: 'completed' })
```

Desired result: The conference ends.
Actual Result: The user who receives the call will be connected to an empty conference with the violin music playing.

### Exception/Log
```
-- BEGIN Twilio API Request --
POST https://api.twilio.com/2010-04-01/Accounts/AC1b1a11fd2831335a20c01882722e05a5/Conferences/CF240108fb51441245cab01ec92dfcf931.json
Headers:
User-Agent: twilio-node/3.59.0 (node.js v15.7.0)
Accept-Charset: utf-8
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Connection: close
-- END Twilio API Request --
response.statusCode: 400
response.headers: {"date":"Wed, 07 Jul 2021 03:51:07 GMT","content-type":"application/json; charset=utf-8","content-length":"113","connection":"close","twilio-request-id":"RQ768e886728ff3567dbe268b8b94c39db","twilio-request-duration":"0.043","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
Error ending the call:  RestException [Error]: Bad request
    at success (/opt/opsiq-be/node_modules/twilio/lib/base/Version.js:88:15)
    at Promise_then_fulfilled (/opt/opsiq-be/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/opt/opsiq-be/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/opt/opsiq-be/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/opt/opsiq-be/node_modules/q/q.js:1369:30)
    at RawTask.call (/opt/opsiq-be/node_modules/asap/asap.js:40:19)
    at flush (/opt/opsiq-be/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (node:internal/process/task_queues:76:11) {
  status: 400,
  code: 20001,
  moreInfo: 'https://www.twilio.com/docs/errors/20001',
  details: undefined
}
```

### Technical details:
* twilio-node version: ^3.55.0
* node version: v15.7.0

**Comment by shwetha-manvinkurke** [comment]
@cmcaboy does the issue occur only while the dialing is in progress? What happens if you try and end the conference after the user has joined the call?

**Comment by cmcaboy** [comment]
@shwetha-manvinkurke That seems to be the case. If I try to end the conference after the user joins the call, it ends appropriately.

**Comment by cmcaboy** [comment]
@shwetha-manvinkurke I did some further research and it seems that the underlying API request is failing.

```
 curl -X POST https://api.twilio.com/2010-04-01/Accounts/ACXXX/Conferences/CFXXX.json --data-urlencode "Status=completed" -u ACXXX:XXX
{"code": 20001, "message": "Bad request", "more_info": "https://www.twilio.com/docs/errors/20001", "status": 400}
```

This was copied straight from the documentation so not sure what the issue is.

**Comment by cmcaboy** [comment]
When fetching the resource, it appears to be in a completed state already:

```
{"status": "completed"}
```

I am assuming that is why I am getting this error.

**Comment by cmcaboy** [comment]
Yes, I figured out that this was because my conference had already ended. Closing...

**Comment by vishaldevmurarili** [comment]
i m facing the same issue could you guys please help me out for this ? i m converting dial call to conference call and some time getting the same issue some times it's works perfectly fine.
