### ISSUE TITLE
Twilio Compositions failed to deserialize for field 'video_layout.transcode.video_sources'

### ISSUE THREAD

**Issue by motat331** [twilio/twilio-node#798]
### Issue Summary
I am attempting to create a video composition using the client.video.v1.compositions.create({}) api, following the documentation here https://www.twilio.com/docs/video/api/compositions-resource?code-sample=code-transcode-a-video-recording&code-language=Node.js&code-sdk-version=3.x

My other Twilio API requests work fine, like creating a room, or retrieving a recording, but this specific request fails 

### Steps to Reproduce
Code Snippet attached

### Code Snippet
```node
const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;
const twilioClient = require("twilio")(accountSid, authToken);

app.post("/api/video/compose", async (req, res) => {
  console.log("Try");
  try {
    const composition = await twilioClient.video.v1.compositions.create({
      videoLayout: {
        transcode: {
          video_sources: "RT2bfd93b2d9f1864ef6b6dedc946b6e6e",
        },
      },
      statusCallback: "https://www.example.com/callbacks",
      format: "mp4",
      roomSid: "RM663c0479f239e4c5513c02f8c9573d5d",
    });
    console.log("Composition: ", composition);
  } catch (e) {
    console.log("Caught E : ", e);
  }
});
```

![image](https://user-images.githubusercontent.com/61713900/192606356-78141dd5-895a-4fe6-b2c4-2138a2cfdd21.png)

### Exception/Log
```
Caught E :  RestException [Error]: Failed to deserialize 'RT2bfd93b2d9f1864ef6b6dedc946b6e6e' for field 'video_layout.transcode.video_sources'
    at success (C:\Apps\randoms\twilio-video-test-nodejs\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Apps\randoms\twilio-video-test-nodejs\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Apps\randoms\twilio-video-test-nodejs\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Apps\randoms\twilio-video-test-nodejs\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Apps\randoms\twilio-video-test-nodejs\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Apps\randoms\twilio-video-test-nodejs\node_modules\asap\asap.js:40:19)
    at flush (C:\Apps\randoms\twilio-video-test-nodejs\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  status: 400,
  code: 400,
  moreInfo: 'https://www.twilio.com/docs/errors/400',
  details: undefined
}
```

### Technical details:
* twilio-node version: ^3.82.0
* node version: v16.13.2

**Comment by childish-sambino** [comment]
Hrm, seeing the same thing locally. I was able to make some progress by wrapping the `video_sources` property in an array. Does this work for you?
```js
video_sources: ["RT2bfd93b2d9f1864ef6b6dedc946b6e6e"],
```

**Comment by mattallard123** [comment]
@childish-sambino solution worked for me! Thanks!
