### ISSUE TITLE
Heroku causes crash due to "MonitorClient is not defined"

### ISSUE THREAD

**Issue by taymoork2** [twilio/twilio-node#91]
Hello, I was upping a quick change to my heroku server, but the following error caused it to crash.
Locally, it works fine (so i don't think it's a problem with the plugin).
Heroku builds the app fine, but when it tries to run, the following error pops up.

Error [output] in question: 

```shell
ReferenceError: MonitorClient is not defined
     MonitorClient = require('./MonitorClient'),
                   ^
/app/node_modules/twilio/lib/index.js:12
     at Function.Module._load (module.js:310:12)
     at Object.<anonymous> (/app/node_modules/twilio/lib/index.js:12:19)
     at require (module.js:384:17)
     at Object.<anonymous> (/app/control_test.js:13:14)
     at Function.cls_wrapMethod (/app/node_modules/newrelic/lib/shimmer.js:230:38)
     at Module.require (module.js:365:17)
     at Module._compile (module.js:460:26)
     at Module.load (module.js:355:32)
     at Module._compile (module.js:460:26)
     at Object.Module._extensions..js (module.js:478:10)
Process exited with status 1
State changed from starting to crashed
```

**Comment by taymoork2** [comment]
self-resolved
problems on my end, do not use --use-strict with your node ... i.e. 'node --use-strict'
